/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
suma_1_svc(numeros *argp, struct svc_req *rqstp)
{
	static float  result;
	float x=argp->x,y=argp->y;
	printf("Se sumaran los numeros %f y %f\n",x,y);
	result=x+y;
	return &result;
}

float *
resta_1_svc(numeros *argp, struct svc_req *rqstp)
{
	static float  result;

	float x=argp->x,y=argp->y;
	printf("Se restaran los numeros %f y %f\n",x,y);
	result=x-y;

	return &result;
}

float *
multp_1_svc(numeros *argp, struct svc_req *rqstp)
{
	static float  result;

	float x=argp->x,y=argp->y;
	printf("Se multiplicaran los numeros %f y %f\n",x,y);
	result=x*y;

	return &result;
}

float *
division_1_svc(numeros *argp, struct svc_req *rqstp)
{
	static float  result;

	float x=argp->x,y=argp->y;
	printf("Se dividiran los numeros %f y %f\n",x,y);
	result=x/y;

	return &result;
}
