/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host,float x,float y)
{
	CLIENT *clnt;
	float  *result;
	int opc;
	numeros  suma_1_arg;
	numeros  resta_1_arg;
	numeros  multp_1_arg;
	numeros  division_1_arg;
	
	suma_1_arg.x=x;
	suma_1_arg.y=y;

	resta_1_arg.x=x;
	resta_1_arg.y=y;
	
	multp_1_arg.x=x;
	multp_1_arg.y=y;

	division_1_arg.x=x;
	division_1_arg.y=y;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	do{
	printf("\tQue operacion deseas realizar?\n");
	printf("1 ==> Suma\n");
	printf("2 ==> Resta\n");
	printf("3 ==> Multiplicacion\n");
	printf("4 ==> Division\n");
	printf("5 ==> Salir\n");
	scanf("%d",&opc);
	switch(opc){
	case 1:
	result = suma_1(&suma_1_arg, clnt);
	if (result == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	break;
	case 2:
	result = resta_1(&resta_1_arg, clnt);
	if (result == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	break;
	case 3:
	result = multp_1(&multp_1_arg, clnt);
	if (result == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	break;
	case 4:
	result = division_1(&division_1_arg, clnt);
	if (result == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	break;
	}
	printf("\nEl resultado es: %f\n",*result);
	}while(opc<5&&opc>0);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float x, y;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	x=atof(argv[2]);
	y=atof(argv[3]);
	calc_prog_1 (host,x,y);
exit (0);
}
