/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	float x;
	float y;
};
typedef struct numeros numeros;

#define CALC_PROG 0x31111111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(numeros *, CLIENT *);
extern  float * suma_1_svc(numeros *, struct svc_req *);
#define RESTA 2
extern  float * resta_1(numeros *, CLIENT *);
extern  float * resta_1_svc(numeros *, struct svc_req *);
#define MULTP 3
extern  float * multp_1(numeros *, CLIENT *);
extern  float * multp_1_svc(numeros *, struct svc_req *);
#define DIVISION 4
extern  float * division_1(numeros *, CLIENT *);
extern  float * division_1_svc(numeros *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULTP 3
extern  float * multp_1();
extern  float * multp_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);

#else /* K&R C */
extern bool_t xdr_numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
